const DATA_CONTRACT_VERSION = 'V1';
const DEFAULT_MACHINE_ID = 'M001';
const STATE_VALUES = Object.freeze(['NORMAL', 'WARNING_VIBRATION', 'WARNING_SOUND', 'WARNING_TEMP', 'CRITICAL_VIB_SOUND', 'CRITICAL_VIB_TEMP', 'CRITICAL_SOUND_TEMP', 'CRITICAL_ALL']);
const RISK_LEVEL_VALUES = Object.freeze(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);
const TREND_VALUES = Object.freeze(['RISING', 'FALLING', 'STABLE']);
const PROBABLE_FAULT_VALUES = Object.freeze(['NONE', 'MECHANICAL_ABNORMALITY', 'OVERHEATING', 'EXCESSIVE_VIBRATION', 'LOOSE_COMPONENT', 'UNKNOWN']);
module.exports = { DATA_CONTRACT_VERSION, DEFAULT_MACHINE_ID, STATE_VALUES, RISK_LEVEL_VALUES, TREND_VALUES, PROBABLE_FAULT_VALUES };
